# -*- coding: utf-8 -*-
"""generating_files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ReASgj5ziBOaixkl3QOb-z6zARjIRU5t

# Reading 10 records for every 5 seconds and stores them as separate files
"""

from random import randint
import time


def main():
    a = 1
    with open('../scats_detector_volume_jan-jun-2020.csv', 'r') as file:
        lines = file.readlines()
        start = 1            # because first line is header
        increment = 10
        end = 11
        total_seconds = 60
        t = 0
        while t <= total_seconds:
            with open('part1/data{}'.format(a), 'w') as writefile:
                writefile.write('\n'.join(line for line in lines[start:end]))
            print('creating file data{}'.format(a))
            a += 1
            start = end
            end = end + increment
            t += 5
            time.sleep(5)


main()

from random import randint
import time


def main():
    a = 1
    with open('../its_scats_sites_aug-2020.csv', 'r') as file:
        lines = file.readlines()
        start = 1            # because first line is header
        increment = 10
        end = 11
        total_seconds = 60
        t = 0
        while t <= total_seconds:
            with open('part2/data{}'.format(a), 'w') as writefile:
                writefile.write('\n'.join(line for line in lines[start:end]))
            print('creating file data{}'.format(a))
            a += 1
            start = end
            end = end + increment
            t += 5
            time.sleep(5)


main()

from random import randint
import time


def main():
    a = 1
    with open('../scats_detector_volume_202002.csv', 'r') as file:
        lines = file.readlines()
        start = 1            # because first line is header
        increment = 10
        end = 11
        total_seconds = 60
        t = 0
        while t <= total_seconds:
            with open('scats_detector/data{}'.format(a), 'w') as writefile:
                writefile.write('\n'.join(line for line in lines[start:end]))
            print('creating file data{}'.format(a))
            a += 1
            start = end
            end = end + increment
            t += 5
            time.sleep(5)


main()

